name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix: 
        os: [macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          ./tests.sh
