name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          ./tests.sh
          
#       - name: Install from Brewfile
#         run: |
#           brew bundle
          
  test-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install zsh
        run: |
          sudo apt install zsh
      
      - name: Run tests
        run: |
          ./tests.sh
      
